name: MobStacker
api-version: 1.7.10
version: '2.0.1'
author: KiwiFisher
main: com.kiwifisher.mobstacker.MobStacker
softdepend: [WorldGuard, mcMMO]
commands:
  mobstacker:
    permission-message: You don't have access to that command!
